// Package docsgen renders the public command reference from the CLI's own cobra
// definitions. The binary and the reference are the same tree, so the two
// cannot drift: cmd/igdev-docs writes the files, and a test fails when a
// committed reference is not what Render produces.
package docsgen

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	"github.com/sheon-sek/igdev/internal/cli"
	"github.com/sheon-sek/igdev/internal/contract"
)

// Dirs are where the reference is written, relative to the repository root.
// docs/reference is the public copy. internal/agentskill/references is the copy
// the Agent Skill embeds and loads on demand; the skill cannot render it at
// runtime because internal/cli imports the skill package. The English reference
// is the only generated one; the zh-CN guide is handwritten and carries no
// generated tables.
var Dirs = []string{"docs/reference", "internal/agentskill/references"}

// header marks every generated file, so a hand edit is visible in review and the
// drift check's message is self-explanatory.
const header = "<!-- Generated by cmd/igdev-docs from the CLI's command definitions. Do not edit: run `make reference` instead. -->\n\n"

// agentContextPath is the command whose page carries the frozen field table:
// its own page is the natural home for the shape of its envelope.
const agentContextPath = "igdev agent context"

// errorsPage is the file name of the error-code reference.
const errorsPage = "errors.md"

// Render returns the whole reference as file name -> content. Every directory in
// Dirs receives the same files. The output is deterministic: the command order
// is cobra's own sorted order.
func Render() map[string]string {
	root := cli.NewDocumentationTree()
	walk(root, func(cmd *cobra.Command) { cmd.InitDefaultHelpFlag() })

	files := map[string]string{
		"README.md": index(root),
		errorsPage:  errors(),
	}
	walk(root, func(cmd *cobra.Command) {
		if cmd == root {
			return
		}
		body := page(cmd, "")
		if cmd.CommandPath() == agentContextPath {
			body = page(cmd, fieldsTable())
		}
		files[slug(cmd)+".md"] = body
	})
	return files
}

// walk visits cmd and every descendant, parents before children.
func walk(cmd *cobra.Command, visit func(*cobra.Command)) {
	visit(cmd)
	for _, child := range cmd.Commands() {
		walk(child, visit)
	}
}

// slug is the file name of one command's page: the command path without the
// binary name, joined with dashes. `igdev` is the index page.
func slug(cmd *cobra.Command) string {
	if cmd.Parent() == nil {
		return "README"
	}
	parts := strings.Fields(cmd.CommandPath())
	return strings.Join(parts[1:], "-")
}

// link is the relative link from a reference page to a command's page.
func link(cmd *cobra.Command) string {
	return slug(cmd) + ".md"
}

// page renders one command: the description the binary prints, plus the usage
// block, options, subcommands, the extra section (when there is one), and the
// Agent usage section, in page form.
func page(cmd *cobra.Command, extra string) string {
	var b strings.Builder
	b.WriteString(header)
	fmt.Fprintf(&b, "# `%s`\n\n", cmd.CommandPath())
	if long := strings.TrimRight(cmd.Long, " \t\r\n"); long != "" {
		b.WriteString(long)
		b.WriteString("\n\n")
	}
	if len(cmd.Commands()) > 0 {
		b.WriteString(subcommands(cmd))
	}
	b.WriteString(codeBlock("Usage", cmd.UseLine(), "\n"))
	if example := strings.Trim(cmd.Example, "\n"); example != "" {
		b.WriteString(codeBlock("Examples", example, "\n"))
	}
	if options := strings.TrimRight(cmd.NonInheritedFlags().FlagUsages(), " \t\r\n"); options != "" {
		b.WriteString(codeBlock("Options", options, "\n"))
	}
	if global := strings.TrimRight(cmd.InheritedFlags().FlagUsages(), " \t\r\n"); global != "" {
		b.WriteString(codeBlock("Global options", global, "\n"))
	}
	b.WriteString(extra)
	if usage := cli.AgentUsage(cmd); usage != "" {
		b.WriteString("## Agent usage\n\n")
		b.WriteString(usage)
		b.WriteString("\n")
	}
	return b.String()
}

// subcommands renders the child list of a command that has one.
func subcommands(cmd *cobra.Command) string {
	var b strings.Builder
	b.WriteString("## Subcommands\n\n")
	b.WriteString("| Command | What it does |\n| --- | --- |\n")
	for _, child := range cmd.Commands() {
		fmt.Fprintf(&b, "| [`%s`](%s) | %s |\n", child.CommandPath(), link(child), child.Short)
	}
	b.WriteString("\n")
	return b.String()
}

// index renders the reference landing page: the root command's own reference
// (the binary's `igdev help` text) followed by the full command list.
func index(root *cobra.Command) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("# igdev command reference\n\n")
	b.WriteString("This reference is generated from the CLI's command definitions; `igdev <command> --help`\n")
	b.WriteString("prints the same text. See [`agent-context.md`](agent-context.md) for the field-by-field\nshape of `igdev agent context --json`, and [`errors.md`](errors.md) for every error code.\n\n")
	if long := strings.TrimRight(root.Long, " \t\r\n"); long != "" {
		b.WriteString(long)
		b.WriteString("\n\n")
	}
	if usage := cli.AgentUsage(root); usage != "" {
		b.WriteString("## Agent usage\n\n")
		b.WriteString(usage)
		b.WriteString("\n\n")
	}
	b.WriteString("## Commands\n\n")
	b.WriteString("| Command | What it does |\n| --- | --- |\n")
	walk(root, func(cmd *cobra.Command) {
		if cmd == root {
			return
		}
		fmt.Fprintf(&b, "| [`%s`](%s) | %s |\n", cmd.CommandPath(), link(cmd), cmd.Short)
	})
	return b.String()
}

// fieldsTable renders the frozen shape of the `agent context --json` data
// object from the field table in internal/cli, which TestAgentContextFields
// checks against the envelope's own struct tags. Nothing here is handwritten.
func fieldsTable() string {
	var b strings.Builder
	b.WriteString("## Data fields\n\n")
	b.WriteString("The `data` member, member by member. Every one is present in every lifecycle\n")
	b.WriteString("state; a nested object is `null` only where the value does not exist yet (there is\nno Instance before `setup`).\n\n")
	b.WriteString("| Field | Type | Meaning |\n| --- | --- | --- |\n")
	for _, f := range cli.AgentContextFields {
		fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", f.Name, f.Type, f.Description)
	}
	b.WriteString("\n")
	return b.String()
}

// errors renders the error-code reference from contract.CodeDocs, which a test
// in internal/contract checks against the declared codes.
func errors() string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("# igdev error codes\n\n")
	b.WriteString("A failed `--json` run prints `ok: false` with one of these codes in `code`. The\n")
	b.WriteString("`remediation` list names the exact command that clears the failure: prefer it over\n")
	b.WriteString("this table. Exit levels are 0 success, 1 command failure, 2 usage error, and 3\n")
	b.WriteString("human action required. At exit 3 an agent stops and hands the Remediation to a person.\n\n")
	b.WriteString("| Code | Exit | Meaning | Next step |\n| --- | --- | --- | --- |\n")
	for _, doc := range contract.CodeDocs {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", doc.Code, doc.Exit, doc.Meaning, doc.Next)
	}
	return b.String()
}

// codeBlock renders a titled fenced block.
func codeBlock(title, body, trail string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "## %s\n\n```text\n%s\n```\n%s", title, body, trail)
	return b.String()
}
