// Command igdev-docs writes the public command reference from the CLI's own
// command definitions. It is the only writer of docs/reference/ and of the Agent
// Skill's internal/agentskill/references/: the committed files are the
// generator's output, and `igdev-docs -check` (the CI step and the drift test in
// internal/docsgen) fails when they are not.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/sheon-sek/igdev/internal/docsgen"
)

func main() {
	check := flag.Bool("check", false, "verify the committed reference matches the command definitions, without writing")
	flag.Parse()

	files := docsgen.Render()
	for _, dir := range docsgen.Dirs {
		run := write
		if *check {
			run = drift
		}
		if err := run(dir, files); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
}

// drift reports every way the committed reference differs from the generated
// one: a changed page, a page the generator no longer produces, and a page it
// produces that is not committed. The message names what to run to fix it.
func drift(dir string, files map[string]string) error {
	var problems []string
	for _, name := range sortedKeys(files) {
		committed, err := os.ReadFile(filepath.Join(dir, name))
		switch {
		case os.IsNotExist(err):
			problems = append(problems, "missing: "+filepath.Join(dir, name))
		case err != nil:
			return err
		case string(committed) != files[name]:
			problems = append(problems, "out of date: "+filepath.Join(dir, name))
		}
	}
	for _, name := range committedPages(dir) {
		if _, ok := files[name]; !ok {
			problems = append(problems, "stale: "+filepath.Join(dir, name))
		}
	}
	if len(problems) > 0 {
		return fmt.Errorf("the committed command reference does not match the command definitions:\n  %s\nrun `make reference` and commit the result",
			strings.Join(problems, "\n  "))
	}
	return nil
}

// write writes every generated page and removes the generated pages the
// generator no longer produces. A file that is not generated is left alone, so
// a hand-written note beside the reference survives.
func write(dir string, files map[string]string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	for _, name := range sortedKeys(files) {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(files[name]), 0o644); err != nil {
			return err
		}
	}
	for _, name := range committedPages(dir) {
		if _, ok := files[name]; ok {
			continue
		}
		path := filepath.Join(dir, name)
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if strings.HasPrefix(string(content), "<!-- Generated by cmd/igdev-docs") {
			if err := os.Remove(path); err != nil {
				return err
			}
		}
	}
	return nil
}

// committedPages lists the Markdown files in dir, ignoring an absent directory.
func committedPages(dir string) []string {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil
	}
	var out []string
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".md") {
			out = append(out, entry.Name())
		}
	}
	sort.Strings(out)
	return out
}

func sortedKeys(files map[string]string) []string {
	out := make([]string, 0, len(files))
	for name := range files {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}
